<?php
    echo $this->doctype();
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Zend Framework2'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->setCharset("utf_8")
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/home.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="row header">
                <div class="navbar-header col-md-3">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Zend Framework 2') ?></a>
                </div>
                <div class="collapse navbar-collapse col-md-5">
                    <ul class="nav navbar-nav">
                        <li><a  class="active" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('首页') ?></a></li>
                        <li><a href="<?php echo $this->url('meeting') ?>"><?php echo $this->translate('聚会') ?></a></li>
                        <li><a href="<?php echo $this->url('forum') ?>"><?php echo $this->translate('论坛') ?></a></li>
                        <li><a href="<?php echo $this->url('Album') ?>"><?php echo $this->translate('我的音乐') ?></a></li>

                        <li id="changeSkin"><a><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> <?php echo $this->translate('换肤') ?></a></li>

                        <li <?php
                        $manager=new \Zend\Session\SessionManager();
                        $sessionContainer=new \Zend\Session\Container();
                        $sessionContainer::setDefaultManager($manager);
                        $user=$sessionContainer->offsetGet("user");
                        if(!isset($user)) echo 'style="display: none"';?>>
                            <a><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a>
                        </li>
                        <li class="welcome" >
                            <?php
                            if(isset($user)) {
                                $url = $this->url('UserCenter');
                                echo '<a href=' . $url . '>' . $user["username"] . '</a>';
                                //var_dump($username);
                            }
                            ?>
                        </li>

                    </ul>

                </div ><!--/.nav-collapse -->
                   <!-- <div class="col-md-2">
                        <li><?php /*session_start();if(isset($_SESSION['email']))echo '<a>edfee</a>';*/?></li>
                    </div>-->
                <div <?php if(isset($user)) echo 'style="display: none"';?>>
                <div class="collapse navbar-collapse col-md-1 login">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm0">登陆</button>
                </div>
                <div class="collapse navbar-collapse col-md-1 register">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">注册</button>
                </div>
                 </div>
               </div>
            </div>
        </nav>

        <div class="modal fade bs-example-modal-sm0" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm">
                <div class="modal-content layout">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">登陆</h4>
                    </div>
                    <div class="modal-body"><!-- 模态框窗口 -->
                        <form action="<?php echo $this->url('User', array('action'=>'login'));?>" method="post">
                            <input type="email" id="email" name="email" required="required" class="form-control" placeholder="请输入账号（邮箱）"/><br/><br/><br/>
                            <input type="password" id="password" name="password" required="required" class="form-control" placeholder="请输入密码"/><br/><br/><br/>
                            <button type="submit" class="btn btn-lg btn-primary btn-block">登陆</button>
                        </form>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm">
                <div class="modal-content layout">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">注册</h4>
                    </div>
                    <div class="modal-body"><!-- 模态框窗口 -->
                        <form action="<?php echo $this->url('User', array('action'=>'register'));?>" method="post">
                            <input type="text" id="username" name="username" required="required" class="form-control" placeholder="请输入喜欢的用户名"/><br/><br/><br/>
                            <input type="email" id="email" name="email" required="required" class="form-control" placeholder="请输入邮箱"/><br/><br/><br/>
                            <input type="password" pattern="[A-z]{6}" title="密码必须为6位字母" id="password" name="password" required="required" class="form-control" placeholder="请输入密码（6位字母）"/><br/><br/><br/>
                            <button type="submit" class="btn btn-lg btn-primary btn-block">注册</button>
                        </form>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
        <div class="container skinView" style="display: none">
            <div class="row">
                <div class="col-xs-6 col-md-3 ">
                    <a href="#" class="thumbnail bg">
                        <img src="<?php echo $this->basePath('img/body_bg.jpg') ?>" alt="...">
                    </a>
                </div>
                <div class="col-xs-6 col-md-3 bg1">
                    <a href="#" class="thumbnail">
                        <img src="<?php echo $this->basePath('img/body_bg1.jpg') ?>" alt="...">
                    </a>
                </div>
                <div class="col-xs-6 col-md-3 bg2">
                    <a href="#" class="thumbnail">
                        <img src="<?php echo $this->basePath('img/body_bg2.jpg') ?>" alt="...">
                    </a>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content;?>
            <hr>
            <audio controls="controls">
                <source src="G:\KuGou\song.mp3" type="audio/ogg">
                <source src="G:\KuGou\song.mp3" type="audio/mpeg">
                Your browser does not support the audio element.
            </audio>
            <footer>
                <p>&copy; 2015 - <?php echo date('Y') ?> by ARTPOPLSH. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 foldChat">
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"> 私信聊天</span>
            </div>

            <div class="chatWindow" style="display: none">
                <div class="chatBoby">
                <div class="chatHead">
                   <span class="chatTitle"></span>
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </div>
                    <div class="dailog">
                        <textarea rows="15" cols="55">

                        </textarea>
                        <input class="form-control editText" placeholder="请输入聊天内容" required="required"/>
                        <input type="button"  class="btn-success" value="发送" id="send"/>
                    </div>
                </div>
                <div class="friendList">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"> 好友列表</span>
                    <ul class="follows">

                    </ul>
                </div>
            </div>

        </div>
    </div>

    </body>
</html>
