<?php
/**
 * Created by PhpStorm.
 * User: lsh_monster
 * Date: 2015/5/8
 * Time: 21:10
 */
$title = '帖子详情';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath() . '/css/forum/detail.css');
$this->headScript()->prependFile($this->basePath() . '/js/forum/detail.js');
?>
<a name="top" id="top"/>
<div class='row'>
    <div class="col-md-10 ">
        <ol class="breadcrumb">
            <li><a href="#">论坛</a></li>
            <li class="active">帖子详细内容</li>
        </ol>
        <div class="readable">
<h3><?php echo $this->escapeHtml($post->title);?></h3>
<span>
    <?php
    echo '发帖人:<a>'.$this->escapeHtml($post->writer).'</a>';
    echo '&nbsp&nbsp&nbsp&nbsp';
    echo $this->escapeHtml($post->time);
    ?>
</span>
<br/><br/>

<p class="content"><?php echo nl2br($this->escapeHtml($post->content));?></p>
    </div>
    </div>
    <div class="icon col-md-2" style="position: fixed;top:300px;left: 80%">
        <a class="btn btn-default btn-lg writeComment" href="#writeComment">
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
        </a><br/>
        <a class="btn btn-default btn-lg" href="#top">
            <span class="glyphicon glyphicon-plane" aria-hidden="true"></span>
        </a>
    </div>

</div>
<div class="commentDiv row">
    <div class="col-md-10">
        <button class="btn btn-primary" type="button">
            评论数  <span class="badge">1</span>
        </button>


    </div>

</div>
<div class="row">
    <div class="col-md-10">
        <a name="writeComment" id="writeComment"></a>
        <form>
            <textarea  class="form-control" rows="3" id="comment" name="comment" required="required"  placeholder="文明评论"></textarea>
            <br/><input id="commentButton" type="button"  class="btn btn-success" value="提交评论"/>
        </form>

    </div>
    <div style="display: none" class="alert alert-warning col-md-3 alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Warning!</strong> 请登陆后在提交评论！
    </div>
</div>