<?php
$title = '帖子浏览';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath() .'/css/forum/index.css');

?>
<ol class="breadcrumb">
    <li><a href="#">论坛</a></li>
    <li class="active">帖子浏览</li>
</ol>

    <button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#myModal" style="margin-bottom: 15px;">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> 我要发帖
    </button>

<div class="tableView">
<table class="table">
    <tr>
        <th>评论数</th>
        <th>标题</th>
        <th>发帖人</th>
        <th>时间</th>
    </tr>
    <?php foreach ($posts as $post) : ?>
        <tr>
            <td><a href="#"><span class="badge"><?php echo $this->escapeHtml($post->commentNum?$post->commentNum:0);?></span></a></td>
            <td><a href="<?php echo $this->url('forum', array('action'=>'detail','id'=>$post->id));?>">
                    <?php echo $this->escapeHtml($post->title);?>
                </a>
            </td>
            <td><?php echo $this->escapeHtml($post->writer);?></td>
            <td><?php echo $this->escapeHtml($post->time);?></td>
        </tr>
    <?php endforeach; ?>
</table>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">我的帖子</h4>
            </div>
            <div class="modal-body">
                <form action="<?php echo $this->url('forum', array('action'=>'add'));?>" method="post">
                    <input type="text" class="form-control" name="title" required="required" placeholder="请输入标题"><br/>
                    <textarea class="form-control" name="content" rows="5" required="required" placeholder="请输入内容"></textarea>
                    <div class="inputDiv"><input type="submit" class="btn btn-primary" value="提交"/>
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                     </div>
                </form>
            </div>
        </div>
    </div>
</div>